services:
    oro_stripe.form.type.settings:
        class: Oro\Bundle\StripeBundle\Form\Type\StripeSettingsType
        arguments:
            - '@translator'
        tags:
            - { name: form.type }

    oro_stripe.form.extension.product_collection:
        class: Oro\Bundle\StripeBundle\Form\Extension\WorkflowTransitionExtension
        tags:
            - { name: form.type_extension, extended_type: Oro\Bundle\WorkflowBundle\Form\Type\WorkflowTransitionType }
