parameters:
    oro_stripe.payment_method.id: 'stripe_payment'

services:
    oro_stripe.payment_method.provider:
        class: Oro\Bundle\StripeBundle\Method\Provider\StripePaymentMethodsProvider
        arguments:
            - '@oro_stripe.method.config_provider'
            - '@oro_stripe.payment_method.factory'

        tags:
            - { name: oro_payment.payment_method_provider }

    oro_stripe.payment_method.factory:
        class: Oro\Bundle\StripeBundle\Method\Factory\StripePaymentMethodFactory
        arguments:
            - '@oro_stripe.payment_action.registry'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: oro_stripe }

    oro_stripe.method.view.provider:
        class: Oro\Bundle\StripeBundle\Method\View\Provider\StripePaymentMethodsViewProvider
        arguments:
            - '@oro_stripe.method.config_provider'
        tags:
            - { name: oro_payment.payment_method_view_provider }

    oro_stripe.method.config_factory:
        class: Oro\Bundle\StripeBundle\Method\Config\Factory\StripePaymentConfigFactory
        arguments:
            - '@oro_stripe.card_method.generator.identifier'
            - '@oro_locale.helper.localization'

    oro_stripe.method.config_provider:
        class: Oro\Bundle\StripeBundle\Method\Config\Provider\StripePaymentConfigsProvider
        arguments:
            - '@doctrine'
            - '@oro_stripe.method.config_factory'

    oro_stripe.card_method.generator.identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%oro_stripe.payment_method.id%'
