api:
    entities:
        Oro\Bundle\CheckoutBundle\Entity\Checkout:
            documentation_resource: '@OroStripeBundle/Resources/doc/api_frontend/checkout.md'
            subresources:
                paymentInfoStripe:
                    target_class: Oro\Bundle\CheckoutBundle\Entity\Checkout
                    actions:
                        add_subresource:
                            description: Apply stripe-related payment information to checkout.
                            request_target_class: Oro\Bundle\StripeBundle\Api\Model\StripePaymentInfoRequest
                        get_subresource: false
                paymentStripe:
                    target_class: Oro\Bundle\OrderBundle\Entity\Order
                    actions:
                        add_subresource:
                            description: Execute checkout payment with stripe payment method
                            request_target_class: Oro\Bundle\StripeBundle\Api\Model\StripePaymentRequest
                        get_subresource: false

        Oro\Bundle\StripeBundle\Api\Model\StripePaymentRequest:
            documentation_resource: '@OroStripeBundle/Resources/doc/api_frontend/checkout.md'
            fields:
                successUrl:
                    data_type: string
                    form_options:
                        constraints:
                            - NotBlank: ~
                failureUrl:
                    data_type: string
                    form_options:
                        constraints:
                            - NotBlank: ~
                partiallyPaidUrl:
                    data_type: string
                    form_options:
                        constraints:
                            - NotBlank: ~
            # this entity does not have own API resource
            actions: false

        Oro\Bundle\StripeBundle\Api\Model\StripePaymentInfoRequest:
            documentation_resource: '@OroStripeBundle/Resources/doc/api_frontend/checkout.md'
            fields:
                stripePaymentMethodId:
                    data_type: string
                    form_options:
                        constraints:
                            - NotBlank: ~
            # this entity does not have own API resource
            actions: false
