operations:

    # Stripe-specific Cancel action with extra field "Cancellation Reason".
    oro_stripe_payment_transaction_cancel:
        extends: oro_payment_transaction_cancel
        attributes:
            cancelReason:
                label: oro.stripe.action.attribute.cancel_reason.label
                type: string
        form_options:
            attribute_fields:
                cancelReason:
                    form_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                    options:
                        placeholder: false
                        choices:
                            oro.stripe.cancel_reason.request_by_customer: requested_by_customer
                            oro.stripe.cancel_reason.duplicate: duplicate
                            oro.stripe.cancel_reason.fraudulent: requested_by_customer
                            oro.stripe.cancel_reason.abandoned: duplicate
                        required: true
                        constraints:
                            -   NotBlank: ~
            attribute_default_values:
                cancelReason:
                    requested_by_customer
        preactions:
            -   '@assign_value':
                    conditions:
                        '@not_empty': $.cancelReason
                    parameters: [ $.transactionOptions, { 'cancelReason': $.cancelReason } ]

    # Stripe-specific Refund action with extra fields "Refund Reason" and "Amount".
    oro_stripe_payment_transaction_refund:
        extends: oro_payment_transaction_refund
        replace:
            - actions
            - preconditions
        attributes:
            amount:
                label: oro.stripe.action.attribute.amount.label
                type: float
            refundReason:
                label: oro.stripe.action.attribute.refund_reason.label
                type: string
        form_options:
            attribute_fields:
                amount:
                    form_type: Symfony\Component\Form\Extension\Core\Type\NumberType
                    options:
                        priority: 5
                        scale: 2
                        constraints:
                            -   Range:
                                    min: 0.00
                                    max: $.availableAmountToRefund
                refundReason:
                    form_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                    options:
                        placeholder: false
                        choices:
                            oro.stripe.refund_reason.request_by_customer: requested_by_customer
                            oro.stripe.refund_reason.duplicate: duplicate
                            oro.stripe.refund_reason.fraudulent: fraudulent
                        required: true
                        constraints:
                            -   NotBlank: ~
            attribute_default_values:
                refundReason:
                    requested_by_customer
                amount: $.availableAmountToRefund
        preactions:
            -   '@call_service_method':
                    service: oro_stripe.provider.transaction_data_provider
                    method: getAvailableAmountToRefund
                    method_parameters: [ $.data ]
                    attribute: $.availableAmountToRefund
            -   '@call_service_method':
                    service: oro_locale.formatter.number
                    method: formatCurrency
                    method_parameters: [ $.availableAmountToRefund, $.data.currency ]
                    attribute: $.amountWithCurrency
            -   '@assign_value':
                    conditions:
                        '@not_empty': $.refundReason
                    parameters: [ $.transactionOptions, { 'refundReason': $.refundReason } ]
        preconditions:
            '@and':
                -   '@acl_granted': [ 'REFUND_PAYMENTS', $.entity ]
                -   '@or':
                        -   '@equal': [ $.data.action, $.purchasePaymentMethodAction ]
                        -   '@equal': [ $.data.action, $.chargePaymentMethodAction ]
                        -   '@equal': [ $.data.action, $.capturePaymentMethodAction ]
                -   '@equal': [ $.data.active, false ]
                -   '@equal': [ $.data.successful, true ]
                -   '@equal': [ $.isActionSupported, true ]
                -   '@not_empty': $.paymentMethod
                -   '@not':
                        -   '@payment_transaction_fully_refunded':
                                transaction: $.data
        actions:
            -   '@payment_transaction_partial_refund':
                    paymentMethodInstance: $.paymentMethod
                    paymentTransaction: $.data
                    transactionOptions: $.transactionOptions
                    amount: $.amount
                    attribute: $.result
            -   '@call_service_method':
                    conditions:
                        '@not_equal': [ $.amount, $.data.amount ]
                    parameters:
                        service: oro_locale.formatter.number
                        method: formatCurrency
                        method_parameters: [ $.amount, $.data.currency ]
                        attribute: $.amountWithCurrency
            -   '@tree':
                    conditions:
                        '@equal': [ '$.result[successful]', true ]
                    actions:
                        -   '@translate':
                                id: 'oro.payment.payment_transaction.note.refund.default_message'
                                attribute: $.noteDefaultMessage
                        -   '@add_string_suffix':
                                attribute: $.note
                                string: $.noteDefaultMessage
                                stringSuffix: $.noteMessage
                        -   '@create_note': [ $.note, $.entity ]
                        -   '@flash_message':
                                message: oro.payment.payment_transaction.refund.result.success
                                message_parameters:
                                    'amount': $.amountWithCurrency
                                type: 'success'
            -   '@flash_message':
                    conditions:
                        '@equal': [ '$.result[successful]', false ]
                    message: '$.result[message]'
                    type: 'error'
