operations:

    # Disables the regular action for the non-Stripe payment methods.
    oro_order_payment_transaction_cancel:
        preactions:
            -   '@assign_value':
                    parameters: [ $.supportedPaymentMethodClasses, [
                        'Oro\Bundle\StripeBundle\Method\StripePaymentMethod',
                        'Oro\Bundle\StripeBundle\Method\StripeAppleGooglePayMethod'
                    ] ]
        preconditions:
            '@and':
                -   '@not_in': [ $.paymentMethodClass, $.supportedPaymentMethodClasses ]

    # Enables the Stripe-specific action for the Stripe payment methods on the Order Payments datagrid.
    oro_stripe_order_payment_transaction_cancel:
        extends: oro_stripe_payment_transaction_cancel
        datagrids:
            - order-payment-transactions-grid
        preactions:
            -   '@assign_value':
                    parameters: [ $.supportedPaymentMethodClasses, [
                        'Oro\Bundle\StripeBundle\Method\StripePaymentMethod',
                        'Oro\Bundle\StripeBundle\Method\StripeAppleGooglePayMethod'
                    ] ]
        preconditions:
            '@and':
                -   '@in': [ $.paymentMethodClass, $.supportedPaymentMethodClasses ]

    # Disables the regular action for the non-Stripe payment methods.
    oro_order_payment_transaction_refund:
        preactions:
            -   '@assign_value':
                    parameters: [ $.supportedPaymentMethodClasses, [
                        'Oro\Bundle\StripeBundle\Method\StripePaymentMethod',
                        'Oro\Bundle\StripeBundle\Method\StripeAppleGooglePayMethod'
                    ] ]
        preconditions:
            '@and':
                -   '@not_in': [ $.paymentMethodClass, $.supportedPaymentMethodClasses ]

    # Enables the Stripe-specific action for the Stripe payment methods on the Order Payments datagrid.
    oro_stripe_order_payment_transaction_refund:
        extends: oro_stripe_payment_transaction_refund
        datagrids:
            - order-payment-transactions-grid
        preactions:
            -   '@assign_value':
                    parameters: [ $.supportedPaymentMethodClasses, [
                        'Oro\Bundle\StripeBundle\Method\StripePaymentMethod',
                        'Oro\Bundle\StripeBundle\Method\StripeAppleGooglePayMethod'
                    ] ]
        preconditions:
            '@and':
                -   '@in': [ $.paymentMethodClass, $.supportedPaymentMethodClasses ]
